[pytest]
testpaths = tests
addopts = -q
filterwarnings =
    ignore:The use of Pydantic less than version 2 is depreciated:DeprecationWarning
    ignore:The 'app' shortcut is now deprecated:DeprecationWarning
